# Arrays

In [1]:
using LinearAlgebra

## Basic syntax

### Vectors

In [2]:
x = [1, 3, 4]

3-element Vector{Int64}:
 1
 3
 4

In [3]:
x'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 1  3  4

In [4]:
4x

3-element Vector{Int64}:
  4
 12
 16

In [5]:
1 .+ x

3-element Vector{Int64}:
 2
 4
 5

In [6]:
sqrt.(x)

3-element Vector{Float64}:
 1.0
 1.7320508075688772
 2.0

In [7]:
g(x) = 3 + 2x^2
g.(x)

3-element Vector{Int64}:
  5
 21
 35

### Matrices

In [8]:
A = [1 4 5;
    3 4 5]

2×3 Matrix{Int64}:
 1  4  5
 3  4  5

In [9]:
5A

2×3 Matrix{Int64}:
  5  20  25
 15  20  25

In [10]:
5 .+ A

2×3 Matrix{Int64}:
 6  9  10
 8  9  10

In [11]:
A * x

2-element Vector{Int64}:
 33
 35

In [12]:
A .^ 2

2×3 Matrix{Int64}:
 1  16  25
 9  16  25

In [13]:
g.(A)

2×3 Matrix{Int64}:
  5  35  53
 21  35  53

### Constructors

In [14]:
zeros(5, 3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [15]:
ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [16]:
rand(5, 3)

5×3 Matrix{Float64}:
 0.642654  0.276619  0.118884
 0.282864  0.590226  0.111319
 0.61387   0.486119  0.438316
 0.90914   0.374246  0.176283
 0.453716  0.241643  0.0507467

In [17]:
ones(5, 5) + I

5×5 Matrix{Float64}:
 2.0  1.0  1.0  1.0  1.0
 1.0  2.0  1.0  1.0  1.0
 1.0  1.0  2.0  1.0  1.0
 1.0  1.0  1.0  2.0  1.0
 1.0  1.0  1.0  1.0  2.0

---

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*