# Arrays

An array is a multi-dimensional collection of objects. The elements of arrays do not
need to be numbers or even from the same type. However, we are interested in numeric
arrays.

In [1]:
using LinearAlgebra

## Basic syntax

### Vectors

In [2]:
x = [1, 3, 4]

3-element Vector{Int64}:
 1
 3
 4

Julia allows to perform operations that are almost globally accepted on vectors. For
example, let's get the transpose:

In [3]:
x'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 1  3  4

Or multiply the vector by an scalar:

In [4]:
4x

3-element Vector{Int64}:
  4
 12
 16

In cases where the operator is not clear, we need to use the dot operator to make
element-by-element computations:

In [5]:
1 .+ x

3-element Vector{Int64}:
 2
 4
 5

In [6]:
sqrt.(x)

3-element Vector{Float64}:
 1.0
 1.7320508075688772
 2.0

The dot operator is atuomatically available for any function:

In [7]:
g(x) = 3 + 2x^2

g (generic function with 1 method)

In [8]:
g.(x)

3-element Vector{Int64}:
  5
 21
 35

### Matrices

In [9]:
A = [1 4 5;
    3 4 5]

2×3 Matrix{Int64}:
 1  4  5
 3  4  5

In [10]:
5A

2×3 Matrix{Int64}:
  5  20  25
 15  20  25

In [11]:
5 .+ A

2×3 Matrix{Int64}:
 6  9  10
 8  9  10

In [12]:
A * x

2-element Vector{Int64}:
 33
 35

In [13]:
A .^ 2

2×3 Matrix{Int64}:
 1  16  25
 9  16  25

In [14]:
g.(A)

2×3 Matrix{Int64}:
  5  35  53
 21  35  53

### Constructors

In [15]:
zeros(5, 3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [16]:
ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [17]:
rand(5, 3)

5×3 Matrix{Float64}:
 0.754165  0.0388548  0.849412
 0.47917   0.588125   0.490492
 0.420275  0.4388     0.173732
 0.748804  0.413649   0.8412
 0.474225  0.527737   0.591853

In [18]:
randn(5, 3)

5×3 Matrix{Float64}:
 -0.868083   0.0978122  -1.09315
  0.180399  -0.143219    1.39829
  0.859611  -1.12529     0.58351
 -0.12067   -1.23975     0.873922
  0.413399  -1.62473     0.492029

In [19]:
ones(5, 5) + I

5×5 Matrix{Float64}:
 2.0  1.0  1.0  1.0  1.0
 1.0  2.0  1.0  1.0  1.0
 1.0  1.0  2.0  1.0  1.0
 1.0  1.0  1.0  2.0  1.0
 1.0  1.0  1.0  1.0  2.0

---

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*